### ISSUE TITLE
使用需求

### ISSUE THREAD

**Issue by Bruce520121-1** [acute-technology-inc/mso-release#1]
你们TravelData(TD3216B)的官方的资料，你们提供了开发接口.DLL，让我们可以根据DGW/TDW/DGV等文件发送波形。
有两个问题： 
 1. 有没有接口，可以生成DGW/TDW/DGV文件呢？当前生成DGW/TDW/DGV文件只能通过Acute Data Generator软件手动生成吗？
2. 有没有根据协议(MIPI RFFE)数据，不用通过生成DGW/TDW/DGV文件，而是直接发送波形的接口？

**Comment by ACUTE-Sen** [comment]
1. 沒有軟件接口, 可使用ACUTE LA轉換波形
2. https://www.acute.com.tw/TmpFiles/DG_PTL_SDK_RFFE_tw_20240531.pdf
